server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    import: optional:file:.env.properties
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: ${APP_NAME:ReadFlow}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  jackson:
    time-zone: UTC

  app:
    webBaseUrl: ${WEB_BASE_URL}

    jwt:
      secret: ${JWT_SECRET}
      expirationMinutes: ${JWT_EXPIRATION_MINUTES}

    email:
      provider: ${EMAIL_PROVIDER:console} # console | resend
      from: ${EMAIL_FROM:ReadFlow <no-reply@readflow.app>}
      resendApiKey: ${RESEND_API_KEY:}

    cloudinary:
      cloudName: ${CLOUDINARY_CLOUD_NAME:}
      apiKey: ${CLOUDINARY_API_KEY:}
      apiSecret: ${CLOUDINARY_API_SECRET:}
      folder: ${CLOUDINARY_FOLDER:readflow}

management:
  endpoints:
    web:
      exposure:
        include: health,info

paystack:
  base-url: ${PAYSTACK_BASE_URL}
  secret-key: ${PAYSTACK_SECRET_KEY}
  currency: ${PAYSTACK_CURRENCY}
  callback-url: ${PAYSTACK_CALLBACK_URL}
